# Generated by Django 5.1.4 on 2024-12-29 01:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('service', '0001_initial'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='client',
            field=models.ForeignKey(limit_choices_to={'role': 'CLIENT'}, on_delete=django.db.models.deletion.RESTRICT, related_name='services', to='user.user'),
        ),
        migrations.AddField(
            model_name='service',
            name='employee',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'EMPLOYEE'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assignments', to='user.user'),
        ),
    ]
